#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppTRAtaMe.Resource", IsApplication=true)]

namespace AppTRAtaMe
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int my_blue = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int my_gray = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int my_green = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int my_purple = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int @checked = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int img_hospital = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int img_hospital_claro = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000c
			public const int btn_borra_foto = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int btn_camara = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int btn_episodio = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int btn_foto = 2131099654;
			
			// aapt resource value: 0x7f06000d
			public const int btn_foto_mas = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int btn_foto_menos = 2131099658;
			
			// aapt resource value: 0x7f060011
			public const int btn_login = 2131099665;
			
			// aapt resource value: 0x7f060005
			public const int btn_respuestas = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int imv_foto = 2131099657;
			
			// aapt resource value: 0x7f060012
			public const int lbl_Resultado = 2131099666;
			
			// aapt resource value: 0x7f06000e
			public const int lbl_conectar = 2131099662;
			
			// aapt resource value: 0x7f060001
			public const int lbl_edad = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int lbl_episodio = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int lbl_episodio_foto = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int lbl_nombre = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int spn_episodio = 2131099651;
			
			// aapt resource value: 0x7f06000f
			public const int txt_nombre = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int txt_password = 2131099664;
			
			// aapt resource value: 0x7f060004
			public const int txt_pregunta = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Episodio = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Foto = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050008
			public const int Borra_Foto = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int Borra_Video = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int Foto = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int Foto_Ant = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int Foto_Sig = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int Video = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public const int Video_Ant = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int Video_Sig = 2131034126;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int conectar = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int episodio_Video = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int episodio_foto = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int episodio_prompt = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int login = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int result = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int serv_no_prompt = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
